sudo: false
language: python

env:
  global:
    - secure: "CXYvdycxFbjbe5D2GZc9XBBWCwxWsO8KfHs9nj8emYxfw15G4Bg9JMafi07OKbQFg90aafSGJWtpGj1qVxF8z34h/F5EYtv8ZamZd5wXrOovItfgDvoNetpOM+j5cBxcSQBzWqynQWXErgxBwXQUfSpKnQ/LMtk7CfpZKRestog="

python:
  - 3.6

install:
  - pip install "Nikola[extras]" commonmark
  - git clone git://github.com/drdoctr/doctr
  - cd doctr
  - python setup.py install

script:
  - set -e
  - nikola build
  - doctr deploy --no-sync --command 'nikola github_deploy' . --no-require-master
