sudo: false
language: python

env:
  global:
    - secure: "H5eFGWu6s6XlG784rLnuJFQeNIyfo1H68XEHOAYVuEtkB7NujBfg/50E3lYJjP7in18lHU6ZESAqc14rFNjPak80K5xxinhBPw1nlLKkg+X/v4mffyCV3TzCsxVX4i4WxC97HTESMTSC06WKuzHmXLdFL6Ja0feFJWAzPrxPChU="

python:
  - 3.6

install:
  - pip install "Nikola[extras]" commonmark doctr

script:
  - set -e
  - nikola build
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      doctr deploy . --built-docs output/;
    else
      doctr deploy --no-require-master "_$TRAVIS_BRANCH" . output/;
    fi
